package com.akexorcist.kotlin.multiplatform.ui.navigation

enum class Screen {
    Cover,
    IntroKotlin,
    KotlinAndAndroid,
    KotlinMultiplatform,
    KotlinMultiplatformLogo,
    PlatformSupport,
    ShareCodeStrategy,
    SharePartialCode,
    ShareLogicCode,
    ShareAllCode,
    PlatformBinary,
    PlatformAndroid,
    PlatformJvm,
    PlatformJs,
    PlatformWasm,
    PlatformNative,
    IdeForKotlinMultiplatform,
    KDoctor,
    Gradle,
    CommonAndSpecificPlatform,
    ProjectStructureModule,
    KotlinMultiplatformWizard,
    PlatformSpecificCode,
    GetStartedWithDemo,
    NativeExperience,
    ComposeMultiplatformIntroduction,
    ComposeMultiplatformBenefit,
    ComposeMultiplatformPlatform,
    ComposeMultiplatformRender,
    ComposeMultiplatformLimitation,
    KotlinMultiplatformBenefit,
    ReadyForProduction,
    CameraAccess,
    MapRendering,
    ThirdPartyAllPlatformLibrary,
    ThirdPartyMobileLibrary,
    PreviewTools,
    OtherLimitation,
    ReallyReadyForProduction,
    DayAndNight,
    BackdropShowcase,
    DecisionMakingFactor,
    Summary1,
    Summary2,
    LearningResource,
    SlideResource,
    ThankYou,

    Introduction,
    AboutKotlin,
    Map,
    CameraViewFinder,
    TitleTemplate,
    SectionTitleTemplate,
    DefaultTemplate,
    RightFrameTemplate,
    LeftFrameTemplate,
    LargeFrameTemplate,
    HighlightStatisticTemplate,
    MultipleContentTemplate,
    MultipleIconContentTemplate,
    RightCustomContentTemplate,
    FullCustomTemplate,
    CodeTemplate,
    CodeCustomContentTemplate,
    ThankYouTemplate,
}

val IndexedScreens = listOf(

//    Screen.Introduction,
//    Screen.ThankYouTemplate,
//    Screen.TitleTemplate,
//    Screen.SectionTitleTemplate,
//    Screen.DefaultTemplate,
//    Screen.RightFrameTemplate,
//    Screen.LeftFrameTemplate,
//    Screen.LargeFrameTemplate,
//    Screen.HighlightStatisticTemplate,
//    Screen.MultipleContentTemplate,
//    Screen.MultipleIconContentTemplate,
//    Screen.RightCustomContentTemplate,
//    Screen.FullCustomTemplate,
//    Screen.CodeTemplate,
//    Screen.CodeCustomContentTemplate,
//    Screen.AboutKotlin,

    Screen.Cover,
    Screen.IntroKotlin,
    Screen.KotlinAndAndroid,
    Screen.KotlinMultiplatform,
    Screen.KotlinMultiplatformLogo,
    Screen.PlatformSupport,
    Screen.ShareCodeStrategy,
    Screen.SharePartialCode,
    Screen.ShareLogicCode,
    Screen.ShareAllCode,
    Screen.PlatformBinary,
    Screen.PlatformAndroid,
    Screen.PlatformJvm,
    Screen.PlatformJs,
    Screen.PlatformWasm,
    Screen.PlatformNative,
    Screen.IdeForKotlinMultiplatform,
    Screen.KDoctor,
    Screen.CommonAndSpecificPlatform,
    Screen.ProjectStructureModule,
    Screen.KotlinMultiplatformWizard,
    Screen.PlatformSpecificCode,
    Screen.GetStartedWithDemo,
    Screen.NativeExperience,
    Screen.ComposeMultiplatformIntroduction,
    Screen.ComposeMultiplatformBenefit,
    Screen.ComposeMultiplatformPlatform,
    Screen.ComposeMultiplatformRender,
    Screen.ComposeMultiplatformLimitation,
    Screen.KotlinMultiplatformBenefit,
    Screen.ReadyForProduction,
    Screen.DayAndNight,
    Screen.CameraAccess,
    Screen.MapRendering,
    Screen.ThirdPartyAllPlatformLibrary,
    Screen.ThirdPartyMobileLibrary,
    Screen.PreviewTools,
    Screen.OtherLimitation,
    Screen.ReallyReadyForProduction,
    Screen.BackdropShowcase,
    Screen.DecisionMakingFactor,
    Screen.Summary1,
    Screen.Summary2,
    Screen.LearningResource,
    Screen.SlideResource,
    Screen.ThankYou,

//    Screen.Introduction,
//    Screen.ThankYouTemplate,
//    Screen.TitleTemplate,
//    Screen.SectionTitleTemplate,
//    Screen.DefaultTemplate,
//    Screen.RightFrameTemplate,
//    Screen.LeftFrameTemplate,
//    Screen.LargeFrameTemplate,
//    Screen.HighlightStatisticTemplate,
//    Screen.MultipleContentTemplate,
//    Screen.MultipleIconContentTemplate,
//    Screen.RightCustomContentTemplate,
//    Screen.FullCustomTemplate,
//    Screen.CodeTemplate,
//    Screen.CodeCustomContentTemplate,
//    Screen.AboutKotlin,
//    Screen.Map,
//    Screen.CameraViewFinder,
)
