target 'iosApp' do
    use_frameworks!
    platform :ios, '17.0'

    pod 'composeApp', :path => '../composeApp'
    pod 'iosPreviewView', :path => '../iosPreviewView'
    pod 'GoogleMaps', '9.0.0'
end
