use_frameworks!
platform :ios, '17.0'

target 'iosApp' do

  # Pods for iosApp
  pod 'composeApp', :path => '../composeApp'
#  pod 'common-ui-kit', :git => 'https://github.com/akexorcist/common-ui-kit.git'
end
